[tool.poetry]
name = "jb-qa"
version = "0.1.0"
description = ""
authors = ["OpenNyAI Team <opennyai@googlegroups.com>"]
readme = "README.md"
packages = [{include = "jugalbandi/qa"}]

[tool.poetry.dependencies]
python = ">=3.10, <4.0.0"
pydantic = "^1.10.8"
asyncpg = "^0.27.0"
gpt-index = "0.5.25"
langchain = "0.0.142"
pypdf2 = "^3.0.1"
cachetools = "^5.3.1"
types-cachetools = "^5.3.0.5"
aiofiles = "^23.1.0"
types-aiofiles = "^23.1.0.3"
jb-core = {path = "../jb-core", develop = true}
jb-document-collection = {path = "../jb-document-collection", develop = true}
jb-speech-processor = {path = "../jb-speech-processor", develop = true}
jb-translator = {path = "../jb-translator", develop = true}
google-cloud-translate = "3.11.1"
python-dotenv = "^1.0.0"
faiss-cpu = "^1.7.4"
pymupdf = "1.22.3"
python-docx = "^0.8.11"
docx2txt = "^0.8"
scikit-learn = "^1.2.2"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.3.0"
flake8 = "^6.0.0"
poethepoet = "^0.20.0"
pytest = "^7.3.1"
pytest-asyncio = "^0.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poe.tasks.lint]
shell = """
black jugalbandi tests
flake8 jugalbandi tests
mypy jugalbandi tests
"""
interpreter = "bash"
help = "format, lint, typecheck"


[tool.poe.tasks.test]
cmd = "python -m pytest -vv -o log_cli=1 -o log_cli_level=INFO -W 'ignore::DeprecationWarning' $FILE"
args = [{name="FILE", default="tests", positional=true}]
help = "run tests using pytest"
